### ISSUE TITLE
ValueError: Input arrays should have the same number of samples as target arrays. Found 63504 input samples and 2000 target samples.

### ISSUE THREAD

**Issue by mouze47** [MaxTitkov/Keras_InceptionV3_Binary_classification#3]
При выполнении файла top_model.py появляется ошибка 
runfile('C:/Keras/top_model.py', wdir='C:/Keras')
train_data.shape[1:] 
(2048, 3, 3)
train_labels.shape[1:] 
[0 0 0 ..., 1 1 1]
validation_data.shape[1:] 
(2048, 3, 3)
validation_labels.shape[1:] 
[0 0 0 ..., 1 1 1]
 
--------------------------------------------------

  ___                  _   _       __   ______  ___ _
 |_ _|_ _  __ ___ _ __| |_(_)___ _ \ \ / /__ / | _ |_)_ _  __ _ _ _ _  _
  | || ' \/ _/ -_) '_ \  _| / _ \ ' \ V / |_ \ | _ \ | ' \/ _` | '_| || |
 |___|_||_\__\___| .__/\__|_\___/_||_\_/ |___/ |___/_|_||_\__,_|_|  \_, |
                 |_|                                                |__/
        
Step_2
Training FFN model with npy arrays saved in last step
--------------------------------------------------
--------------------------------------------------
Fitting train and val .npy arrays to top_model...
Traceback (most recent call last):

  File "<ipython-input-15-65dfc1ad4072>", line 1, in <module>
    runfile('C:/Keras/top_model.py', wdir='C:/Keras')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 707, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Keras/top_model.py", line 53, in <module>
    model.fit(train_data, train_labels, epochs=epochs1, batch_size=32, validation_data=(validation_data, validation_labels))

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py", line 863, in fit
    initial_epoch=initial_epoch)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1358, in fit
    batch_size=batch_size)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1246, in _standardize_user_data
    _check_array_lengths(x, y, sample_weights)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 237, in _check_array_lengths
    'and ' + str(list(set_y)[0]) + ' target samples.')

ValueError: Input arrays should have the same number of samples as target arrays. Found 63504 input samples and 2000 target samples.

Help to fix the error.

**Comment by mouze47** [comment]
I use Windows 10, Anaconda3  (Python 3.6.2) with Theano (0.9.0) and Keras (2.0.6).

**Comment by MaximPedich** [comment]
https://github.com/MaxTitkov/Keras_InceptionV3_Binary_classification/blob/35575517f6721c248ffb070b9bf03d59c537e2bc/top_model.py#L46

В этом месте выдает ошибку:
> ValueError: Input arrays should have the same number of samples as target arrays. Found 63566 input samples and 2000 target samples.

Мне кажется, это результат аугментации данных на предыдущем этапе (bottleneck_features.py).
Сталкивались ли вы с подобной ошибкой?

**Comment by Ramil-Ming** [comment]
таже самая ошибка. В чем причина?
